universe    =   vanilla
executable  =   trainMVAAll.sh
arguments   =   $(Tree) $(Method)

log         =   /user/nivanden/condor/logs/trainMVA_$(Method)_$(ClusterId)_$(Process).log
error       =   /user/nivanden/condor/error/trainMVA_$(Method)_$(ClusterId)_$(Process).err
output      =   /user/nivanden/condor/output/trainMVA_$(Method)_$(ClusterId)_$(Process).out

queue 1 Tree, Method from (
    DL_tree, DL_BDT
    DL_tree, DL_NN
    ML_tree, ML_BDT
    ML_tree, ML_NN
)
