executable = MainAnalysis.sh
arguments = $(Samplelist) $(Method) timestamp=2023-09-19_14-00

output = /user/nivanden/condor/output/analysis_exec_$(method)_$(ClusterId)_$(ProcId).out
error = /user/nivanden/condor/error/analysis_exec_$(method)_$(ClusterId)_$(ProcId).err
log = /user/nivanden/condor/logs/analysis_exec_$(method)_$(ClusterId)_$(ProcId).log

queue 1 Samplelist, Method from (
	test_EFT_Sample.txt, MCPrompt
)


