executable = TreeAnalysis.sh
arguments = $(Samplelist) $(Method) $(Syst) 2024-04-04_14-42 condorrun

output = /user/nivanden/condor/output/Analysis_$(Method)_$(ClusterId).$(ProcId).out
error = /user/nivanden/condor/error/Analysis_$(Method)_$(ClusterId).$(ProcId).out
log = /user/nivanden/condor/logs/Analysis_$(Method)_$(ClusterId).$(ProcId).log

queue 1 Samplelist, Method, Syst from (
	TmpLists/2017_fullStat_TTHH_0.txt MCPrompt nominal
)
